import {useEffect,useRef,useState} from 'react';
import {request} from './studio/api';
import {money,policyPath,type S} from './studio/model';
import './demo.css';

const label=(id:string|null)=>id==='fixture-small-local'?'Compact · small fixture':id==='fixture-medium-local'?'Extended · medium fixture':id==='fixture-over-budget'?'Over-budget fixture':id?'Other-region fixture':'Unknown configuration';
const id=()=>crypto.randomUUID();
const outputSchema:S['JsonSchema-Input']={type:'object',properties:{category:{type:'string',required:[]},reply:{type:'string',required:[]}},required:['category','reply'],additionalProperties:false};
export default function DemoStudio(){
  const [manifest,setManifest]=useState<S['DemoManifest']>(),[selected,setSelected]=useState('fast'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [status,setStatus]=useState('Ready to choose a task'),[run,setRun]=useState<S['SandboxRun']>(),[output,setOutput]=useState(''),[streamId,setStreamId]=useState('');
  const [usage,setUsage]=useState<S['UsageSummary']>(),[comparison,setComparison]=useState<S['ComparisonResult']>(),[compOutputs,setCompOutputs]=useState<Record<string,unknown>>({});
  const [toolCalls,setToolCalls]=useState<S['ToolCall'][]>([]),[toolResult,setToolResult]=useState('');
  const abort=useRef<AbortController|null>(null), activeRun=useRef<string|null>(null), stopped=useRef(false);
  const chosen=manifest?.scenarios.find(s=>s.id===selected);
  const attempts=[...(usage?.attempts??[])].sort((a,b)=>a.usage.observed_at.localeCompare(b.usage.observed_at));
  const [ttfc,setTtfc]=useState<number>(),[elapsed,setElapsed]=useState<number>();
  const [fallback,setFallback]=useState(false);
  const decision=fallback?manifest?.fallback:chosen;
  function clearResult(){setRun(undefined);setStreamId('');setTtfc(undefined);setElapsed(undefined);setToolResult('');}
  async function refresh(){setUsage(await request<S['UsageSummary']>('/api/studio/usage'));}
  useEffect(()=>{void request<S['DemoManifest']>('/api/studio/demo').then(setManifest).catch(e=>setError(String(e)));void refresh();},[]);
  async function action(work:()=>Promise<void>){setBusy(true);setError('');stopped.current=false;try{await work();}catch(e){setError(String(e));setStatus('Stopped — inspect the saved attempts before retrying');}finally{setBusy(false);abort.current=null;activeRun.current=null;await refresh().catch(()=>{});}}
  async function enable(ref:S['VersionRef'],admission:string){const path=policyPath(ref);const view=await request<S['PolicyView']>(path);if(view.transition.status!=='sandbox_enabled')await request(path+'/transitions',{expected_sequence:view.transition.sequence,status:'sandbox_enabled',admission_id:admission});}
  async function waitRun(runId:string){for(let i=0;i<240;i++){if(stopped.current)throw new Error('Stopped; usage may remain pending.');const value=await request<S['SandboxRun']>(`/api/sandbox/runs/${runId}`);setRun(value);setStatus(`Workflow ${value.status}`);if(!['queued','running'].includes(value.status))return value;await new Promise(r=>setTimeout(r,250));}throw new Error('Worker deadline: inspect saved run; no automatic retry.');}
  async function runWorkflow(){if(!chosen)return;clearResult();setOutput('');setToolCalls([]);setFallback(false);setComparison(undefined);setStatus('Enabling this exact sandbox policy…');await enable(chosen.policy,chosen.admission_id);const value=await request<S['SandboxRun']>('/api/sandbox/runs',{policy:chosen.policy,inputs:chosen.inputs},id());activeRun.current=value.id;sessionStorage.setItem('demo-last-run',value.id);const finished=await waitRun(value.id);const rows=await request<S['StoredOutput'][]>(`/api/sandbox/runs/${value.id}/outputs`);setOutput(rows.map(o=>typeof o.value==='object'?JSON.stringify(o.value,null,2):String(o.value)).join('\n'));if(finished.status!=='succeeded')throw new Error(`Workflow ${finished.status}; no successful output is implied.`);}
  async function withKey(s:S['DemoScenario'],work:(secret:string)=>Promise<void>){const key=await request<S['IssuedKey']>('/api/studio/keys',{expires_at:new Date(Date.now()+1800000).toISOString(),scopes:['models:read','chat:complete','runs:read'],alias_ids:[s.alias],workflow_policies:[],max_cost_micro_usd:1000});try{await work(key.secret);}finally{await request(`/api/studio/keys/${key.metadata.id}/revoke`,{});}}
  function chatBody(s:S['DemoScenario'],stream:boolean):S['ChatCompletionRequest']{return {model:s.alias,messages:[{role:'user',content:s.task+(s.id==='fallback'?` DEMO_FAIL_ONCE ${id()}`:'')}],max_tokens:128,stream,...(s.tools.length?{tools:s.tools,tool_choice:'auto'}: {})};}
  async function streamStage(s:S['DemoScenario']){clearResult();if(s.id==='fallback')setSelected('fast');setOutput('');setToolCalls([]);setToolResult('');setFallback(s.id==='fallback');setComparison(undefined);setTtfc(undefined);setElapsed(undefined);await enable(s.policy,s.admission_id);setStatus('Connecting to the sandbox stage…');const started=performance.now();let first=false;let text='';const calls:S['ToolCall'][]=[];await withKey(s,async secret=>{const controller=new AbortController();abort.current=controller;const response=await fetch('/v1/chat/completions',{method:'POST',signal:controller.signal,headers:{'Content-Type':'application/json','Authorization':'Bearer '+secret,'Idempotency-Key':id()},body:JSON.stringify(chatBody(s,true))});const requestId=response.headers.get('X-Request-ID')??'';setStreamId(requestId);if(requestId)sessionStorage.setItem('demo-last-stream',requestId);if(!response.ok)throw new Error(`Stream request rejected (${response.status})`);const reader=response.body?.getReader();if(!reader)throw new Error('Readable stream unavailable');const decoder=new TextDecoder();let buffer='',done=false,bytes=0;
    while(true){const chunk=await reader.read();if(chunk.done)break;bytes+=chunk.value.length;if(bytes>1048576){controller.abort();throw new Error('Stream exceeded display bound');}buffer+=decoder.decode(chunk.value,{stream:true});const frames=buffer.split('\n\n');buffer=frames.pop()??'';for(const frame of frames){const data=frame.split('\n').filter(l=>l.startsWith('data:')).map(l=>l.slice(5).trim()).join('\n');if(!data)continue;if(data==='[DONE]'){done=true;continue;}const value=JSON.parse(data);if(value.error)throw new Error(value.error.message);const delta=value.choices?.[0]?.delta;if(delta?.content){if(!first){setTtfc(Math.round(performance.now()-started));first=true;}text+=delta.content;setOutput(text);setStatus('Streaming stage output…');}for(const tool of delta?.tool_calls??[]){const n=tool.index??0;calls[n]??={id:'',type:'function',function:{name:'',arguments:''}};if(tool.id)calls[n].id=tool.id;if(tool.function?.name)calls[n].function.name+=tool.function.name;if(tool.function?.arguments)calls[n].function.arguments+=tool.function.arguments;}}}
    if(!done)throw new Error('Incomplete stream: no successful terminal event.');setToolCalls(calls);setStatus(calls.length?'Read-only tool requested — approval required':'Stream completed and persisted');setElapsed(Math.round(performance.now()-started));});}
  async function approveTool(){
    setTtfc(undefined);setElapsed(undefined);
    if(!chosen||toolCalls.length!==1)throw new Error('One known tool required');
    const call=toolCalls[0];
    if(call.function.name!=='lookup_support'||call.function.arguments!=='{"key":"shipping"}')throw new Error('Undeclared tool or argument denied');
    const result='Standard shipping takes 3 business days.';setToolResult(result);
    await withKey(chosen,async secret=>{
      const body=chatBody(chosen,false);
      body.messages=[{role:'user',content:chosen.task},{role:'assistant',content:null,tool_calls:toolCalls},{role:'tool',content:result,tool_call_id:call.id}];
      async function complete(payload:S['ChatCompletionRequest']){
        const response=await fetch('/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+secret,'Idempotency-Key':id()},body:JSON.stringify(payload)});
        const value=await response.json();if(!response.ok)throw new Error(value.error?.message??'Stage request rejected');return value;
      }
      const continuation=await complete(body);
      if(stopped.current)throw new Error('Stopped before separate schema call');
      const checked=await complete({model:chosen.alias,messages:[{role:'user',content:chosen.task+'\nRead-only tool result: '+result+'\nDraft reply: '+continuation.choices[0].message.content}],max_tokens:128,stream:false,response_format:{type:'json_schema',json_schema:{name:'support_reply',schema:outputSchema,strict:true}}});
      setOutput(checked.choices[0].message.content);setStatus('Structured reply validated in a separate call; original tool ID preserved in the preceding round trip');setToolCalls([]);
    });
  }
  async function compare(){if(!chosen?.alternative||!chosen.alternative_admission)return;setComparison(undefined);await enable(chosen.policy,chosen.admission_id);await enable(chosen.alternative,chosen.alternative_admission);const sample:S['ImportedSample-Input']={execution_schema:'2.0',provenance:'user_imported_not_verified',tool_schemas:[],id:id(),kind:'sample',inputs:chosen.inputs,expected_output:chosen.expected,expected_reviewed:true,source_label:'Stakeholder demo deterministic fixture v1',imported_at:new Date().toISOString(),data_class:'synthetic',processing:'approved_hosted',retention_days:1,split:'holdout'};await request('/api/studio/imports',sample);const budget={max_cost_micro_usd:0,max_input_tokens:4096,max_output_tokens:256,max_model_calls:2,max_tool_calls:0,max_attempts:1,timeout_ms:120000};const created=await request<S['ComparisonResult']>('/api/studio/comparisons',{sample_ids:[sample.id],policies:[chosen.policy,chosen.alternative],budget},id());setStatus('Comparing the same sample on two pinned policies…');for(const cell of created.cells)await waitRun(cell.run_id!);const result=await request<S['ComparisonResult']>(`/api/studio/comparisons/${created.id}`);const values:Record<string,unknown>={};for(const cell of result.cells){if(cell.output_reference)values[cell.output_reference]=(await request<S['StoredOutput']>(`/api/studio/outputs/${cell.output_reference}`)).value;}setCompOutputs(values);setComparison(result);setStatus('Comparison complete — no automatic winner');}
  async function restore(){const last=sessionStorage.getItem('demo-last-stream');if(last){const row=await request<S['StoredOutput']>(`/api/studio/outputs/${last}`);setOutput(JSON.stringify(row.value,null,2));setStreamId(last);setStatus('Loaded persisted stream result — no new execution');return;}const lastRun=sessionStorage.getItem('demo-last-run');if(lastRun){setRun(await request<S['SandboxRun']>(`/api/sandbox/runs/${lastRun}`));setOutput(JSON.stringify(await request(`/api/sandbox/runs/${lastRun}/outputs`),null,2));setStatus('Loaded saved workflow — no new execution');}}
  return <div className="shell demo"><aside><a className="brand" href="?demo=1">Buildbox</a><p className="aside-note">One workflow.<br/>The right model configuration.<br/>A route you can inspect.</p><a className="aside-link" href={chosen?`/?plan=${chosen.plan.id}&version=${chosen.plan.version}&policy=${chosen.policy.id}%40${chosen.policy.version}`:'/'}>Open full workflow studio →</a></aside><main><header>OPEN-MODEL ROUTER <span className="pill">Stakeholder demo</span></header><h1>Describe the work.<br/><span>Understand the route.</span></h1><p className="intro">Match workflow requirements to model configurations, run a controlled route, and inspect the result and every attempt.</p><p className="demo-banner">Demo execution — routing/product behavior is real; upstream model responses and catalog capability/price facts are simulated. No live provider charges.</p>
    {error&&<p role="alert" className="error">{error}</p>}{!manifest&&<p>Loading the isolated demo… Start with <code>make demo</code>.</p>}
    {manifest&&chosen&&<><section id="demo-task"><h2>1. Choose the task</h2><div className="demo-options">{manifest.scenarios.map(s=><button key={s.id} className={selected===s.id?'':'secondary'} disabled={busy} onClick={()=>{setSelected(s.id);clearResult();setOutput('');setComparison(undefined);setToolCalls([]);setToolResult('');setError('');setFallback(false);setStatus('Ready');}}>{s.title}</button>)}</div><h3>Task</h3><p>{chosen.task}</p><div className="demo-tags">{chosen.requirements.map(r=><span className="pill" key={r}>{r}</span>)}</div><p className="muted">Preconfigured requirements, not live language-model interpretation. Use the full studio to edit a task, prompts or policy versions.</p></section>
    <section id="demo-decision"><h2>2. Routing decision</h2><h3>{label(decision?.selected??null)}</h3><p>Provider: simulated / synthetic-provider · Policy: <code>{decision?.policy.id}@{decision?.policy.version}</code></p><p className="route-reason">{decision?.explanation}</p><p>Decision basis: deterministic filtering + cost order{selected==='review'?' + explicit reviewer pin':''}. Quality: provisional; not benchmarked.</p><details><summary>Alternatives considered</summary><div className="demo-candidates">{manifest.catalog.configurations.map(c=>{const checks=decision?.assessments[c.id]??[];const failed=checks.filter(f=>f.value!==true);return <article key={c.id}><h3>{label(c.id)}</h3><p>{c.id===decision?.selected?'Selected':failed.length?'Excluded':'Eligible alternative'} · Catalog price: {c.cost_per_1k_tokens.value===null?'unknown':`$${c.cost_per_1k_tokens.value} / 1k tokens (synthetic)`}</p><p>{failed.length?failed.map(f=>f.provenance.source.split(':').pop()?.replaceAll('_',' ')).join('; '):'Passes the recorded hard requirements'}</p><p>Latency: unknown — not benchmarked.</p></article>;})}</div></details><details><summary>Machine-readable evidence</summary><pre>{JSON.stringify(decision?.assessments,null,2)}</pre></details></section>
    <section id="demo-run"><h2>3. Enable & run</h2><p>These actions explicitly enable the exact sandbox policy and start bounded simulated calls. Each new action is accounted separately; viewing saved data does not run it again.</p><div className="actions"><button disabled={busy} onClick={()=>void action(runWorkflow)}>Run workflow</button><button disabled={busy} onClick={()=>void action(()=>streamStage(chosen))}>Stream stage output</button><button className="secondary" disabled={busy} onClick={()=>void action(()=>streamStage(manifest.fallback))}>Demonstrate safe fallback</button>{chosen.alternative&&<button className="secondary" disabled={busy} onClick={()=>void action(compare)}>Compare alternate route</button>}</div>{busy&&<button className="secondary" onClick={()=>{stopped.current=true;abort.current?.abort();if(activeRun.current)void request(`/api/sandbox/runs/${activeRun.current}/cancel`,{});setStatus('Stop requested — pending charges remain accounted');}}>Stop current action</button>}<p role="status">{status}</p>{fallback&&<p className="notice">Small fixture → controlled pre-response 503 → allowed medium fallback. The failed attempt remains visible; unknown usage is not silently refunded.</p>}{output&&<><h3>Returned output</h3><pre className="demo-output" aria-live="polite">{output}</pre></>}{toolCalls.length>0&&<div className="notice"><h3>Read-only tool request</h3><pre>{JSON.stringify(toolCalls,null,2)}</pre><p>Simulated shipping lookup only. The chat API does not execute tools secretly; approval supplies the original call ID, then makes a separate schema-constrained reply. Approval starts two accounted stage calls because this API does not combine tool history with strict JSON delivery.</p><button disabled={busy} onClick={()=>void action(approveTool)}>Approve read-only lookup</button></div>}{toolResult&&<p>Tool result: {toolResult} (synthetic policy)</p>}<p>Browser first content: {ttfc===undefined?'not measured':`${ttfc} ms`} · browser completion: {elapsed===undefined?'not measured':`${elapsed} ms`}. Includes deliberately paced simulator/network time, not model performance.</p>{run&&<p>Persisted workflow: <code>{run.id}</code> · {run.status}</p>}{streamId&&<p>Stage request: <code>{streamId}</code></p>}<button className="secondary" disabled={busy} onClick={()=>void action(restore)}>Load last saved result</button></section>
    {comparison&&<section id="demo-comparison"><h2>Same input, alternative routes</h2><p>One sample per policy; expected answer is a fixture. No quality winner can be inferred.</p><div className="demo-compare">{comparison.cells.map(c=><article key={c.policy.id}><h3>{c.policy.id}@{c.policy.version}</h3><p>{c.status} · {c.completion_ms??'unknown'} ms workflow completion</p><pre>{JSON.stringify(c.output_reference?compOutputs[c.output_reference]:'No output',null,2)}</pre>{c.checks?.map(check=><p key={check.check}>{check.check}: {check.status}</p>)}</article>)}</div></section>}
    <section id="demo-accounting"><h2>4. Results & accounting</h2><button className="secondary" disabled={busy} onClick={()=>void action(refresh)}>Refresh recorded usage</button>{usage&&<><p>{usage.attempts.length} persisted attempts · recorded subtotal {money(usage.known_subtotal_micro_usd)} · {usage.unresolved_attempts} unknown/pending. Simulated token/cost reports; elapsed times measured locally.</p><div className="demo-table"><table><thead><tr><th>Route / configuration</th><th>Attempt</th><th>Status</th><th>Tokens</th><th>Cost</th><th>Elapsed</th></tr></thead><tbody>{attempts.slice(-12).map(a=><tr key={a.id}><td>{a.trace.policy.id}@{a.trace.policy.version}<br/>{label(a.trace.configuration_id)}</td><td>{a.attempt}</td><td>{a.status}<br/>{a.usage.state}</td><td>{a.usage.tokens?.total_tokens??'unknown'}</td><td>{money(a.usage.actual_micro_usd)}</td><td>{a.latency_ms??'unknown'} ms</td></tr>)}</tbody></table></div></>}</section><footer><p>To connect live: approve exact provider targets, evidence, credentials, privacy/retention and spending limits. Existing runtime checks remain mandatory. This local demo is not production-ready.</p><button className="secondary" disabled={busy} onClick={()=>{clearResult();setFallback(false);sessionStorage.removeItem('demo-last-run');sessionStorage.removeItem('demo-last-stream');setOutput('');setRun(undefined);setComparison(undefined);setToolCalls([]);setError('');setStatus('View reset; audit history preserved. For a fresh demo, stop and rerun make demo.');}}>Reset presentation</button></footer></>}
  </main></div>;
}
