import {useEffect, useState} from 'react';
import type {components} from './generated/api';
import {request} from './studio/api';
import './demo.css';

type S=components['schemas'];
const root='/api/studio/intelligence';
const preset=(id:string):Partial<S['RouterPolicy']>=>({id,version:1,weights:id==='speed'?{latency:1}:id==='quality'?{quality:1}:id==='cost'?{cost:1}:{quality:.35,latency:.2,cost:.25,privacy:.1,reliability:.1}});
const metric=(v:number|null|undefined,unit='')=>v==null?'Unknown':`${Number(v.toFixed(3))}${unit}`;

export default function IntelligenceStudio(){
  const [access,setAccess]=useState<S['AdvancedStatus']>(),[description,setDescription]=useState(''),[catalog,setCatalog]=useState('');
  const [overrides,setOverrides]=useState('{"input_tokens":4096,"output_tokens":128}'),[profile,setProfile]=useState<S['WorkloadProfile']>();
  const [decision,setDecision]=useState<S['RoutingDecision']>(),[original,setOriginal]=useState<S['RoutingDecision']>(),[policy,setPolicy]=useState<S['ExecutablePolicy-Output']>();
  const [objective,setObjective]=useState<Partial<S['RouterPolicy']>>(preset('balanced')),[terms,setTerms]=useState<string[]>([]);
  const [input,setInput]=useState(''),[admission,setAdmission]=useState(''),[consent,setConsent]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [status,setStatus]=useState('Describe a workload or choose a deterministic example.'),[run,setRun]=useState<S['SandboxRun']>(),[outputs,setOutputs]=useState<S['StoredOutput'][]>([]),[attempts,setAttempts]=useState<S['RunAttempt'][]>([]);
  const [outcomes,setOutcomes]=useState<S['ExecutionOutcome'][]>([]),[rating,setRating]=useState(3),[allHistory,setAllHistory]=useState(false),[graph,setGraph]=useState<S['ExecutionPlan']|null>(null);
  const [evaluation,setEvaluation]=useState<S['PolicyEvaluationReport']>();
  async function action(work:()=>Promise<void>){setBusy(true);setError('');try{await work();}catch(e){setError(String(e));}finally{setBusy(false);}}
  function accept(value:S['RoutingDecision']){setDecision(value);setDescription(value.objective);setCatalog(value.catalog.id);setOverrides(JSON.stringify(value.profile,null,2));setObjective(value.router_policy);setTerms(value.required_terms);setGraph(value.execution_plan??null);setProfile(value.profile);setPolicy(undefined);setAdmission('');setConsent(false);const url=new URL(location.href);url.searchParams.set('decision',value.id);history.replaceState(null,'',url);}
  useEffect(()=>{void action(async()=>{const value=await request<S['AdvancedStatus']>(root+'/status');setAccess(value);setCatalog(value.catalog_ids.find(c=>c.startsWith('advanced-'))??value.catalog_ids[0]??'');const saved=new URLSearchParams(location.search).get('decision');if(saved)accept(await request<S['RoutingDecision']>(root+'/decisions/'+encodeURIComponent(saved)));});},[]);
  function explicit():Partial<S['WorkloadProfile']>{if(new TextEncoder().encode(overrides).length>16000)throw new Error('Override size limit exceeded');const parsed=JSON.parse(overrides);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error('Overrides must be a JSON object');return parsed;}
  async function analyze(){setProfile(await request<S['WorkloadProfile']>(root+'/analyze',{description,overrides:explicit()}));setStatus('Workload profile analyzed locally; no provider or research call.');}
  async function preview(){const value=await request<S['RoutingDecision']>(root+'/preview',{description,catalog_id:catalog,overrides:explicit(),policy:objective,required_terms:terms,execution_plan:graph});accept(value);setOriginal(value);setStatus(value.status==='ready'?'Route preview saved; not activated.':'No valid plan satisfies all hard constraints.');}
  async function scenario(s:S['AdvancedScenario']){setDescription(s.request.description);setInput(s.input);setOverrides(JSON.stringify(s.request.overrides,null,2));setCatalog(s.request.catalog_id);setObjective(s.request.policy??preset('balanced'));setTerms(s.request.required_terms??[]);const value=await request<S['RoutingDecision']>(root+'/decisions/'+s.decision_id);accept(value);setOriginal(value);if(s.policy)setPolicy(await request<S['PolicyView']>(`/api/studio/policies/${s.policy.id}/versions/${s.policy.version}`).then(v=>v.policy));setAdmission(s.admission_id??'');setOutputs([]);setRun(undefined);setAttempts([]);setStatus('Loaded pinned synthetic scenario; no execution yet.');}
  async function whatIf(mode:string){if(!decision)return;const selected=preset(mode);const value=await request<S['RoutingDecision']>(root+`/decisions/${decision.id}/what-if`,{policy:selected});setOriginal(original??decision);accept(value);setObjective(selected);setStatus('What-if saved separately. Original decision and enabled routes unchanged; no model calls.');}
  async function makeDraft(){if(!decision)return;setPolicy(await request<S['ExecutablePolicy-Output']>(root+'/drafts',{decision_id:decision.id}));setStatus('Executable draft saved. New exact-version admission is required before running.');}
  async function refreshRun(id:string){const value=await request<S['SandboxRun']>(`/api/sandbox/runs/${id}`);setRun(value);setOutputs(await request<S['StoredOutput'][]>(`/api/sandbox/runs/${id}/outputs`));const all=await request<S['UsageSummary']>('/api/studio/usage');setAttempts(all.attempts.filter(a=>a.run_id===id));setOutcomes(await request<S['ExecutionOutcome'][]>(root+'/outcomes'));return value;}
  async function execute(){if(!policy||!consent||!admission)throw new Error('Review inputs and approve the exact admitted sandbox policy.');const path=`/api/studio/policies/${policy.id}/versions/${policy.version}`;const view=await request<S['PolicyView']>(path);if(view.transition.status!=='sandbox_enabled')await request(path+'/transitions',{expected_sequence:view.transition.sequence,status:'sandbox_enabled',admission_id:admission});const value=await request<S['SandboxRun']>('/api/sandbox/runs',{policy:{id:policy.id,version:policy.version},inputs:{input}},crypto.randomUUID());setRun(value);setAllHistory(false);setOutputs([]);setStatus('Workflow queued; waiting for actual stage checkpoints.');for(let i=0;i<240;i++){const current=await refreshRun(value.id);setStatus(`Workflow ${current.status}`);if(!['queued','running'].includes(current.status))return;await new Promise(r=>setTimeout(r,500));}throw new Error('Polling deadline; inspect saved run before any new execution.');}
  async function evaluate(){if(!decision)return;setEvaluation(await request<S['PolicyEvaluationReport']>(root+'/evaluate',{decisions:[decision.id],experimental:preset('quality')}));setStatus('Decision-only policy comparison saved; no model-quality conclusion.');}
  return <div className="shell demo"><aside><a className="brand" href="?intelligence=1">Buildbox</a><p className="aside-note">Give us the workload.<br/>Inspect the strategy.</p><a className="aside-link" href="/">Full workflow studio</a><a className="aside-link" href="?demo=1">Original demo A–C</a></aside><main><header>WORKLOAD INTELLIGENCE <span className="pill">Sandbox</span></header><h1>Which model, where,<br/><span>and why?</span></h1><p className="intro">Requirements → evidence → execution strategy → an inspectable, versioned route.</p>{access?.synthetic&&<p className="demo-banner">Real routing and runtime; examples use synthetic model/deployment facts, benchmarks and responses. No live quality claim.</p>}{error&&<p className="error" role="alert">{error}</p>}<p role="status">{status}</p>
    <section><h2>1. Describe the workload</h2>{access?.scenarios.length?<div className="demo-options">{access.scenarios.map(s=><button className="secondary" key={s.id} disabled={busy} onClick={()=>void action(()=>scenario(s))}>{s.id} · {s.title}</button>)}</div>:null}<label>Workload<textarea rows={3} value={description} onChange={e=>{setDescription(e.target.value);setGraph(null);}} placeholder="What input, outcome and constraints matter?"/></label><label>Catalog snapshot<select value={catalog} onChange={e=>setCatalog(e.target.value)}>{access?.catalog_ids.map(id=><option key={id}>{id}</option>)}</select></label>{access&&!access.catalog_ids.length&&<p>No owned catalog snapshot is available. Use the existing workflow studio or an approved runtime registry; discovery alone is not execution access.</p>}<details><summary>Explicit requirements override inference</summary><p>Unknown answers may stay null. Set input/output envelopes, strategy, privacy, maximum cost/latency/calls, required capabilities or minimum task-specific quality. Edits below do not change a saved route until you preview.</p><textarea aria-label="Explicit workload overrides" rows={9} value={overrides} onChange={e=>{setOverrides(e.target.value);setGraph(null);}}/></details><div className="actions"><button disabled={busy||!description.trim()} onClick={()=>void action(analyze)}>Analyze workload</button><button disabled={busy||!description.trim()||!catalog} onClick={()=>void action(preview)}>Preview route</button></div></section>
    {profile&&<section><h2>2. Understood requirements</h2><div className="demo-tags"><span className="pill">{profile.task} · {profile.complexity}</span><span className="pill">Input envelope {profile.input_tokens??'unknown'} · output {profile.output_tokens??'unknown'}</span><span className="pill">{profile.local_only?'Local only':profile.self_hosted_only?'Self-hosted only':'Approved runtime required'}</span></div><p>Required: {profile.required.join(', ')}. Output: {profile.structured_output}. Strategy preference: {profile.strategy}.</p>{profile.questions.map(q=><p key={q}>{q}</p>)}<details><summary>Inference and override evidence</summary><pre>{JSON.stringify(profile,null,2)}</pre></details></section>}
    {decision&&<><section><h2>3. Execution plan & routing decision</h2><p>{decision.strategy_reason}</p><p>Worst-case calls: {decision.max_model_calls} · projected cost {metric(decision.projected_cost_micro_usd,' micro-USD')} · critical path {metric(decision.projected_latency_ms,' ms')} ({decision.catalog.synthetic?'synthetic estimates':'estimates, not guarantees'}).</p><p>Catalog {decision.catalog.id} · router policy {decision.router_policy.id}@{decision.router_policy.version}</p>{decision.blockers.map(b=><p className="error" key={b}>{b}</p>)}<div className="demo-candidates">{decision.stages.map(s=><article key={s.node_id}><h3>{s.node_id} → {s.selected??'Blocked'}</h3><p>After: {s.depends_on.join(', ')||'input'} · task: {s.profile.task} · Routing confidence: {s.routing_confidence} · Model-quality confidence: {s.quality_confidence}</p><p className="route-reason">{s.explanation}</p>{decision.execution_plan?.stages.filter(n=>n.id===s.node_id&&n.validators.length>0).map(n=><p key={n.id}>Generate → validate ({n.validators.map(v=>v.kind).join(', ')}) → {n.max_repairs?`repair on failure, at most ${n.max_repairs}; validate again`:'finish or bounded failure'}. {n.escalate?'Higher-evidence escalation is permitted within the same cap.':''}</p>)}{s.fallbacks.length>0&&<p>Validation escalation: {s.fallbacks.join(' → ')}</p>}<details><summary>Candidate tradeoffs & exclusions</summary>{s.candidates.map(c=><div key={c.configuration_id}><h4>{c.configuration_id} · {c.eligible?(c.pareto?'Pareto-efficient':'Eligible'):'Excluded'}</h4><p>{c.rejected.join('; ')}</p>{c.eligible&&<p>Task quality {metric(c.metrics?.quality)} · {metric(c.metrics?.latency,' ms')} · {metric(c.metrics?.cost,' micro-USD')} · utility {metric(c.utility)}</p>}<p>Unknown: {c.unknown.join(', ')||'none among weighted metrics'}; {c.conflicts.join('; ')}</p><small>{Object.entries(c.metric_basis??{}).map(([k,v])=>`${k}: ${v}`).join(' · ')}</small></div>)}</details></article>)}</div><details><summary>Complete decision trace and evidence</summary><pre>{JSON.stringify(decision,null,2)}</pre></details></section>
    <section><h2>4. Explore the tradeoff</h2><p>What-if and shadow comparison change decisions only. They never call a model or migrate enabled routes.</p><div className="actions">{['balanced','quality','cost','speed'].map(mode=><button className="secondary" key={mode} disabled={busy} onClick={()=>void action(()=>whatIf(mode))}>Prioritize {mode}</button>)}<button className="secondary" disabled={busy} onClick={()=>void action(evaluate)}>Evaluate shadow policy</button></div>{original&&original.id!==decision.id&&<p>Original: {original.stages.map(s=>s.selected).join(' → ')}. What-if: {decision.stages.map(s=>s.selected).join(' → ')}. Cost delta {original.projected_cost_micro_usd!=null&&decision.projected_cost_micro_usd!=null?metric(decision.projected_cost_micro_usd-original.projected_cost_micro_usd,' micro-USD'):'unknown'}.</p>}{evaluation&&<p>{evaluation.case_count} router-behavior case(s); disagreement {metric(evaluation.disagreement_rate*100,'%')}. No model quality conclusion.</p>}</section>
    <section><h2>5. Review and execute safely</h2><button disabled={busy||decision.status!=='ready'} onClick={()=>void action(makeDraft)}>Prepare executable draft</button>{policy&&<><p>Exact policy: {policy.id}@{policy.version}. Quality remains provisional.</p><details><summary>Executable prompts and typed input bindings</summary><pre>{JSON.stringify({prompts:policy.prompts,stages:policy.stages},null,2)}</pre></details><a href={`/?plan=${policy.plan.id}&version=${policy.plan.version}&policy=${policy.id}%40${policy.version}`}>Edit prompts / inspect history / API examples in full studio →</a><label>Sample input<textarea rows={3} value={input} onChange={e=>setInput(e.target.value)}/></label><label>Operator-issued exact-version admission<input value={admission} onChange={e=>setAdmission(e.target.value)}/></label><label className="check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I reviewed the inputs and approve this exact sandbox execution.</label><button disabled={busy||!consent||!admission||!input} onClick={()=>void action(execute)}>Enable sandbox & run</button></>}{run&&<><p>Saved run {run.id} · {run.status} · policy {run.policy.id}@{run.policy.version}</p>{['running','queued'].includes(run.status)&&<button className="secondary" onClick={()=>void request(`/api/sandbox/runs/${run.id}/cancel`,{}).catch(e=>setError(String(e)))}>Stop run</button>}<p>Outputs below arrive at persisted stage checkpoints, not simulated token streaming.</p>{outputs.map(o=><article key={o.id}><h3>{o.node_id}</h3><pre>{JSON.stringify(o.value,null,2)}</pre></article>)}{attempts.map(a=><article key={a.id}><h4>{a.node_id} · {a.trace.configuration_id} · attempt {a.attempt}</h4><p>{a.status} {a.failure_kind??''} {a.recovery_action?`· ${a.recovery_action} after ${a.fallback_reason}`:''} · {metric(a.latency_ms,' ms')} · {a.usage.tokens?.total_tokens??'unknown'} tokens · {metric(a.usage.actual_micro_usd,' micro-USD')} ({a.usage.state})</p>{a.validation?.map((v,i)=><p key={i}>{v.kind}: {v.passed?'pass':'fail'} — {v.detail}</p>)}</article>)}<button className="secondary" disabled={busy} onClick={()=>void action(async()=>{await refreshRun(run.id);})}>Refresh saved run (no execution)</button></>}</section></>}
    <section><h2>Outcome history</h2><p>Content-free execution observations, at most 1000 retained records. Ratings are explicit user feedback, not benchmark truth. Outcomes do not alter ranking. Attempt latency is summed work, not parallel wall time.</p><button className="secondary" disabled={busy} onClick={()=>void action(async()=>{setOutcomes(await request<S['ExecutionOutcome'][]>(root+'/outcomes'));setAllHistory(true);})}>Load outcome history</button>{outcomes.filter(o=>allHistory||!run||o.run_id===run.id).map(o=><article key={o.run_id}><h3>{o.status} · {o.synthetic?'Synthetic upstream':'Runtime observation'}</h3><p>{o.attempt_count} attempts · {o.repair_count} repairs · {o.fallback_count} fallbacks · {o.failed_validations} failed checks · final validation {o.validation_passed==null?'not evaluated':o.validation_passed?'passed':'failed'}</p><p>{o.known_cost_micro_usd} known micro-USD · {o.unknown_cost_attempts} unknown-cost attempts · {metric(o.attempt_latency_ms,' ms summed attempt time')}</p><p>Policy {o.policy.id}@{o.policy.version} · catalog {o.catalog_id} · rating {o.rating??'not provided'}</p>{o.rating==null&&<><label>Explicit user rating (1–5)<select value={rating} onChange={e=>setRating(Number(e.target.value))}>{[1,2,3,4,5].map(v=><option key={v}>{v}</option>)}</select></label><button disabled={busy} onClick={()=>void action(async()=>{await request(root+'/outcomes/'+o.run_id+'/rating',{rating});setOutcomes(await request<S['ExecutionOutcome'][]>(root+'/outcomes'));})}>Save explicit rating</button></>}</article>)}</section>
  </main></div>;
}
