import { useState } from 'react';
import { request } from './api';
import { apiExamples, identifier, parseInputs, policyPath, ref, refKey, renderPrompt, type S } from './model';
export default function Routes({value,onChange,onRun}: {value?:S['PolicyView'];onChange:(v:S['PolicyView'])=>void;onRun:(id:string)=>void}) {
  const [admission,setAdmission]=useState(''),[confirmed,setConfirmed]=useState(false),[aliasId,setAliasId]=useState(''),[nodeId,setNodeId]=useState(''),[alias,setAlias]=useState<S['RouteAlias']>();
  const [inputs,setInputs]=useState('{}'),[preview,setPreview]=useState<S['WorkflowRunRequest']['inputs']>(),[runConfirm,setRunConfirm]=useState(false),[origin,setOrigin]=useState(location.origin);
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[language,setLanguage]=useState<'curl'|'python'|'typescript'>('curl');
  async function act(work:()=>Promise<void>){setBusy(true);setError('');try{await work();}catch(e){setError(String(e));}finally{setBusy(false);}}
  const code=alias?(()=>{try{return apiExamples(alias,origin,value&&refKey(value.policy)===refKey(alias.policy)?value.policy.stages.find(s=>s.node_id===alias.node_id)?.budget.max_output_tokens:1)[language];}catch(e){return String(e);}})():'';
  return <section id="routes"><h2>Routes & developer access</h2><p>Sandbox activation is not production approval. Alias pins never move when a draft or catalog changes.</p>
    {!value?<p>Save or load an executable draft in the step editor first.</p>:<><h3>{refKey(value.policy)} · {value.transition.status}</h3><p>Transition #{value.transition.sequence} · {value.policy.quality} · production approval: false.</p>
      <fieldset disabled={busy}><label>Operator-issued admission ID<input value={admission} placeholder="Required for enabling; this UI cannot issue one" onChange={e=>{setAdmission(e.target.value);setConfirmed(false);}} /></label>
      <label className="check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} />I explicitly approve the requested sandbox state change for this exact version.</label>
      <div className="actions"><button disabled={!confirmed||!identifier.test(admission)||value.transition.status==='sandbox_enabled'} onClick={()=>void act(async()=>{onChange(await request<S['PolicyView']>(`${policyPath(value.policy)}/transitions`,{execution_schema:'2.0',expected_sequence:value.transition.sequence,status:'sandbox_enabled',admission_id:admission} satisfies S['TransitionRequest']));setConfirmed(false);})}>Enable this sandbox version</button>
      <button className="secondary" disabled={!confirmed||value.transition.status==='disabled'} onClick={()=>void act(async()=>{onChange(await request<S['PolicyView']>(`${policyPath(value.policy)}/transitions`,{execution_schema:'2.0',expected_sequence:value.transition.sequence,status:'disabled',admission_id:null} satisfies S['TransitionRequest']));setConfirmed(false);})}>Disable this version</button></div></fieldset>
      <p className="hint">Operator admission must verify privacy, license, access, capabilities, authorization and spending. Unknown quality may remain provisional. Enabling an older exact version is an explicit rollback only if its admission is still valid; it never repins another alias. Load the old version in the editor and review it first.</p>
      <details><summary>Single-stage API alias</summary><div className="form-grid"><label>Alias ID<input value={aliasId} onChange={e=>{setAliasId(e.target.value);setAlias(undefined);}} /></label><label>LLM stage<select value={nodeId} onChange={e=>setNodeId(e.target.value)}><option value="">Select stage</option>{value.policy.stages.filter(s=>s.configuration_id).map(s=><option key={s.node_id}>{s.node_id}</option>)}</select></label></div><div className="actions"><button disabled={busy||!identifier.test(aliasId)||!nodeId} onClick={()=>void act(async()=>{const stage=value.policy.stages.find(s=>s.node_id===nodeId);if(!stage?.configuration_id)throw new Error('Select a pinned LLM stage.');setAlias(await request<S['RouteAlias']>('/api/studio/aliases',{execution_schema:'2.0',id:aliasId,policy:ref(value.policy.id,value.policy.version),node_id:nodeId,configuration_id:stage.configuration_id,created_at:new Date().toISOString(),environment:'sandbox'} satisfies S['RouteAlias']));})}>Create immutable alias</button><button className="secondary" disabled={busy||!identifier.test(aliasId)} onClick={()=>void act(async()=>setAlias(await request<S['RouteAlias']>(`/api/studio/aliases/${aliasId}`)))}>Load saved alias</button></div>
        {alias&&<><p>{alias.id} → {refKey(alias.policy)} / {alias.node_id} / {alias.configuration_id}. Accessible alias metadata is not proof your application key can call it.</p><label>Runtime API base URL<input value={origin} onChange={e=>setOrigin(e.target.value)} /></label><label>Example language<select value={language} onChange={e=>setLanguage(e.target.value as typeof language)}><option value="curl">cURL</option><option value="python">Python</option><option value="typescript">TypeScript</option></select></label><pre>{code}</pre><button className="secondary" onClick={()=>void act(async()=>{await navigator.clipboard.writeText(code);})}>Copy example</button><p>Set a fresh BUILDBOX_REQUEST_ID for new work; preserve it when inspecting an uncertain submission. GET /v1/models lists aliases authorized for your application key. POST /v1/chat/completions calls one model/stage, not the whole workflow. Supported: model, text messages, max_tokens, temperature, stream. Tools, n, provider overrides, response_format and other parameters are rejected.</p></>}
      </details>
      <h3>Run a supported sample workflow</h3><p>Input types: <code>{JSON.stringify(value.policy.input_types)}</code> · up to {value.policy.budget.max_model_calls} model calls / {value.policy.budget.max_tool_calls} tool calls · cap {value.policy.budget.max_cost_micro_usd} micro-USD. These are bounds, not an estimate or permission.</p>
      <label>Named sample inputs JSON<textarea rows={4} value={inputs} onChange={e=>{setInputs(e.target.value);setPreview(undefined);setRunConfirm(false);}} /></label><button className="secondary" onClick={()=>{try{setPreview(parseInputs(inputs,value.policy.input_types));setError('');}catch(e){setError(String(e));}}}>Preview executable input and prompts</button>
      {preview&&<><pre>{JSON.stringify(preview,null,2)}</pre>{value.policy.stages.map(stage=>{const prompt=value.policy.prompts?.find(p=>p.id===stage.prompt?.id&&p.version===stage.prompt.version);const node=value.policy.workflow.nodes.find(n=>n.id===stage.node_id)!;const bound=Object.fromEntries(Object.entries(node.inputs??{}).filter(([,binding])=>binding.from_input).map(([key,binding])=>[key,preview[binding.source]]));return <details key={stage.node_id} open><summary>{stage.node_id} · {stage.configuration_id??stage.operation??'approval/tool stage'}</summary><pre>{prompt?renderPrompt(prompt,bound):JSON.stringify({bindings:node.inputs,operation:stage.operation,tools:stage.allowed_tool_ids},null,2)}</pre></details>;})}
      <label className="check"><input type="checkbox" checked={runConfirm} onChange={e=>setRunConfirm(e.target.checked)} />This sample is synthetic, contains no secrets, and I approve a new sandbox run within the displayed cap.</label>
      <button disabled={busy||!runConfirm||value.transition.status!=='sandbox_enabled'||uncertain} onClick={()=>void act(async()=>{setRunConfirm(false);setUncertain(true);const run=await request<S['SandboxRun']>('/api/sandbox/runs',{execution_schema:'2.0',policy:ref(value.policy.id,value.policy.version),inputs:preview,sample_reference:null} satisfies S['WorkflowRunRequest'],crypto.randomUUID());setUncertain(false);onRun(run.id);})}>Run sample (new costed action)</button></>}
      {uncertain&&<p className="notice">Submission did not return a confirmed run. No automatic retry. Inspect server request state before starting another run; this view prevents duplicate submission.</p>}
      {value.transition.status!=='sandbox_enabled'&&<p>Run blocked: this pinned policy is not sandbox-enabled.</p>}
    </>}
    <details><summary>Application keys & provider connections</summary><p>Unavailable in the frozen HTTP contract: key create/revoke, allowed-route/budget metadata and safe provider-connection status. No credential form or pretend connection is provided. The integration owner must compose the canonical key/credential ports and authenticated metadata endpoints.</p><p>Application keys and provider keys are different. Never paste a provider key into this page or code examples. No key is stored in browser storage.</p></details>
    {error&&<p role="alert" className="error">{error}</p>}
  </section>;
}
